[package]
name = "tedge_actors"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
futures = { version = "0.3" }
log = "0.4"
thiserror = "1.0"
tokio = { version = "1.22", default_features = false, features = ["sync", "rt", "macros"] }

[dev-dependencies]
tokio = { version = "1.22", default_features = false, features = ["time"] }