[package]
name = "tedge_actors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
futures = { version = "0.3", features = ["executor", "thread-pool"] }
thiserror = "1.0"

[dev-dependencies]