[package]
name = "tedge_actors"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
futures = { version = "0.3" }
log = "0.4"
thiserror = "1.0"
tokio = { version = "1.23", default_features = false, features = [
    "sync",
    "rt",
    "macros",
    "time"
] }

[dev-dependencies]
env_logger = "0.10" # TODO: remove me
tokio = { version = "1.23", default_features = false, features = [
    "rt-multi-thread",
] }

[package.metadata.docs.rs]
rustdoc-args = ["--test"]
