[package]
name = "add_timestamp"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = { workspace = true }
wit-bindgen = { workspace = true }
wit-bindgen-rt = { workspace = true }

[lib]
crate-type = ["cdylib"]


