[package]
name = "group_by_timestamp"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
time = { workspace = true }
wit-bindgen = { workspace = true }

[lib]
crate-type = ["cdylib"]