[package]
name = "tedge_http_ext"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }
tedge_actors = { path = "../../core/tedge_actors" }
url = "2.3"
thiserror = "1.0"
