[package]
name = "tedge_http_ext"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
futures = { version = "0.3" }
http = "0.2"
hyper = { version = "0.14", default_features = false, features = ["client", "http1", "http2", "tcp"] }
serde = "1.0"
serde_json = "1.0"
tedge_actors = { path = "../../core/tedge_actors" }
thiserror = "1.0"
tokio = { version = "1.22", default_features = false, features = ["macros", "rt"] }
