[package]
name = "tedge_mqtt_ext"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
mqtt_channel = { path = "../../common/mqtt_channel" }
tedge_actors = { path = "../../core/tedge_actors" }
tokio = { version = "1.22", default_features = false, features = ["macros"] }

[dev-dependencies]
mqtt_tests = { path = "../../tests/mqtt_tests" }
