[package]
name = "c8y_configuration_poc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
tedge_actors = { path = "../../core/tedge_actors" }
tokio = { version = "1.8", features = ["rt", "rt-multi-thread"] }