[package]
name = "c8y_configuration_poc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
c8y_api = { path = "../../core/c8y_api" }
mqtt_channel = { path = "../../common/mqtt_channel" }
tedge_actors = { path = "../../core/tedge_actors" }
tedge_config = { path = "../../common/tedge_config" }
tedge_http_ext = { path = "../../extensions/tedge_http_ext" }
tedge_utils = { path = "../../common/tedge_utils", features = ["fs-notify"] }
tokio = { version = "1.8", features = ["rt", "rt-multi-thread"] }
try-traits = { version = "0.1" }
