[package]
name = "c8y_configuration_poc"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
c8y_api = { path = "../../core/c8y_api" }
csv = "1.1"
download = { path = "../../common/download" }
env_logger = "0.10"
hyper = { version = "0.14", default_features = false }
log = "0.4"
mqtt_channel = { path = "../../common/mqtt_channel" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tedge_actors = { path = "../../core/tedge_actors" }
tedge_api = { path = "../../core/tedge_api" }
tedge_config = { path = "../../common/tedge_config" }
tedge_http_ext = { path = "../../extensions/tedge_http_ext" }
tedge_signal_ext = { path = "../../extensions/tedge_signal_ext" }
tedge_utils = { path = "../../common/tedge_utils", features = ["fs-notify"] }
thiserror = "1.0"
tokio = { version = "1.8", features = ["rt", "rt-multi-thread"] }
toml = "0.5"
tracing = { version = "0.1", features = ["attributes", "log"] }
try-traits = { version = "0.1" }
